name: Build and Release Flutter App

on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_windows:
    name: Build Windows App
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: windows-release-build
          path: build/windows/x64/runner/Release

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_android, build_windows]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: release-apk
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: windows-release-build
          path: windows-build
      - name: Zip Windows build
        run: zip -r windows-release.zip ./windows-build
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-apk/app-release.apk
            windows-release.zip